export const baseText = `Qu’en est-il si on examine les choses chronologiquement ? Je ne peux reprendre, bien sûr, que quelques-uns des éléments d’une très riche démonstration.

À la fin du XVIIIe siècle, l’État social n’est pas à l’ordre du jour de la bourgeoisie révolutionnaire, mais les sociétés de secours mutuel, embryon de la Sociale, vont concentrer l’attention de la classe dirigeante au XIXe siècle. C’est l’objet du décret du 26 mars 1852 légalisant la mutualité. Je cite Nicolas Da Silva : « Alors que les mutuelles sont des lieux de socialisation ouvrière potentiellement subversifs où se pense la transformation sociale par l’auto-organisation, il s’agit d’en faire des institutions intégrées à l’ordre social », de changer « le sens de la mutuelle : d’une institution d’émancipation dirigée contre le capital et l’État à une institution de gestion de la souffrance créée par le capitalisme industriel. […] Les mutuelles “approuvées” donnent de nombreux avantages en contrepartie d’un contrôle politique fort des élites de l’Empire, tandis que les mutuelles “autorisées” ne bénéficient d’aucun avantage et s’exposent aux forces de la répression par leur refus de l’approbation. Sommés de choisir l’un ou l’autre statut juridique, les militants se séparent entre ceux qui acceptent l’ordre établi et ceux qui, en conservant leur autonomie, le combattent ». Et – toujours la collusion entre l’État et le capital – « alors que les sociétés de secours mutuel étaient organisées en fonction des métiers, les mutuelles approuvées sont principalement organisées sur une base territoriale […]. L’organisation spatiale plutôt que professionnelle a pour objectif d’empêcher que les mutuelles servent à défendre les intérêts des ouvriers face aux employeurs ». Cependant que « l’institutionnalisation des membres honoraires a pour objectif explicite de “moraliser” la classe ouvrière, c’est-à-dire d’empêcher que les buts de secours soient détournés, en particulier pour organiser la conflictualité de classe ». On retrouve « l’histoire de la lutte entre démocratie et représentation telle qu’elle commence en 1789. L’État autorise les ouvriers attachés aux principes démocratiques à s’auto-organiser, mais c’est pour mieux les surveiller et les réprimer. À ceux qui acceptent la délégation de pouvoir, via le rôle du préfet, du clergé et des membres honoraires, l’État offre des avantages matériels importants ».

Si je cite longuement ce passage sur la mutualité du Second Empire, c’est que, comme le montre en détail la suite de l’ouvrage, la République va s’appuyer sur elle contre le syndicalisme tandis que l’État social du XXe siècle l’utilisera dans les assurances sociales de 1930 avant de l’instrumenter de nouveau depuis 1947 pour combattre toute renaissance de l’auto-organisation instituée à vaste échelle de 1946 à 1967 dans le régime général. Car contre la Sociale, la « forme non capitaliste » de la mutualité en fait un cheval de Troie particulièrement efficace du couple État social/capital.

Venons-en maintenant à la naissance de l’État social et à l’affirmation de son contraire, la Sociale.

« Le soin, écrit Nicolas Da Silva, est un sujet politique et de politique publique bien avant la première moitié du XXe siècle. Cependant, ce n’est qu’avec les deux guerres mondiales que l’on constate l’explosion du secteur des soins dans les dépenses de l’État. Pour comprendre le lien entre guerre totale et État social, il est nécessaire de déplacer le regard que l’on porte habituellement sur les périodes de guerre. Ce ne sont pas des parenthèses entre deux cycles de paix, ce sont des périodes fondatrices d’un nouvel ordre trouvant ses racines dans la préparation, la conduite et les conséquences de la guerre. La Grande Guerre (1914-1918) modifie la place de l’État dans la société, rendant possible ce qui était autrefois impossible : l’adoption des assurances sociales de 1928-1930. L’État ne devient social que parce qu’il a organisé la guerre totale. »

`;

export const baseTextSimple =
  '(3)\n(3)This is a simple base text. It has multiple lines.\n\nAnd another one.\nAnd another one.';
